### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by tooh** [jeeftor/AlfredSonosTTS#1]
Plugin does not produce a .mp3 message

TypeError: not all arguments converted during string formatting
Logged from file tts.py, line 15
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file tts.py, line 15

4:10:20 workflow.py:1774 DEBUG    data `voice` stored as `cpickle`
14:10:20 workflow.py:1789 DEBUG    stored data loaded: /Users/peter/Library/Application Support/Alfred 3/Workflow Data/org.jeef.sonos/voice.cpickle
14:10:20 workflow.py:1774 DEBUG    data `speaker_name` stored as `cpickle`
14:10:20 workflow.py:1789 DEBUG    stored data loaded: /Users/peter/Library/Application Support/Alfred 3/Workflow Data/org.jeef.sonos/speaker_name.cpickle
14:10:20 workflow.py:1657 DEBUG    reading settings from /Users/peter/Library/Application Support/Alfred 3/Workflow Data/org.jeef.sonos/settings.json
14:10:20 workflow.py:2440 DEBUG    set last run version: 1.0.11
14:10:20 workflow.py:2289 DEBUG    ---------- finished in 0.040s ----------

**Comment by jeeftor** [comment]
Hmm. What string did you try?

**Comment by tooh** [comment]
Thx for your reply. Issue occurs with any text, f.i. tts "test" or tts test

ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

Python 2.7.10
